---
- name: Configure OSPF
  hosts: R1
  gather_facts: no
  tasks:
    - name: Configure OSPF on routers
      ios_command:
        commands:
          - "router ospf 1"
          - "network 192.168.1.0 0.0.0.255 area 0"
      become: yes
      become_method: enable
      become_pass: cisco
      tags: ospf

