---
- name: Configure Router Interface
  hosts: Router
  gather_facts: no  # We don't need facts gathering for this task
  become: true
  tasks:
    - name: Configure Interface
      ios_config:
        lines:
          - interface GigabitEthernet0/2
          - ip address 192.168.1.2 255.255.255.0
        parents: interface GigabitEthernet0/2
      register: config_result
      timeout: 60

    - name: Display Configuration Result
      debug:
        var: config_result
