---
- name: Retrieve Running Configuration
  hosts: R4  # Replace with your host or host group
  gather_facts: no
  tasks:
    - name: Show Running Configuration
      ios_command:
        commands:
          - show running-config
      register: running_config
      become_method: enable

    - name: Display Running Configuration
      debug:
        var: running_config.stdout_lines

