---
- name: Configure Router Interface
  hosts: R1
  gather_facts: no
  become: yes
  tasks:
    - name: Configure Interface
      ios_config:
        lines:
          - interface GigabitEthernet0/3
          - description My New Interface
          - no shutdown
          - ip address 192.168.1.1 255.255.255.0
      register: config_result

